lms/urls.py
from django.contrib import admin
from django.urls import path, include

from core_lms.views import index

urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

students/urls.py
from django.urls import path

from students.views import get_students, create_student, update_student, \
    delete_student

app_name = 'students'

urlpatterns = [
    path('', get_students, name='list_students'),
    path('create', create_student, name='create_students'),
    path('update/<int:id>', update_student, name='update_students'),
    path('delete/<int:id>', delete_student, name='delete_students'),
]

core_lms/models.py
from django.db import models

# Create your models here.

students/models.py
import datetime
import random

from django.core.validators import MinValueValidator, MaxValueValidator, \
    RegexValidator
from django.db import models
from django.urls import reverse
from faker import Faker

# Create your models here.
from core_lms.validators import even_integer_validator


class Student(models.Model):
    first_name = models.CharField(max_length=64, null=False)
    last_name = models.CharField(max_length=64, null=False)
    age = models.IntegerField(default=20, validators=[
        MinValueValidator(20),
        MaxValueValidator(120),
        even_integer_validator
    ])
    email = models.EmailField(max_length=64)
    phone_number = models.CharField(
        max_length=24,
        validators=[
            RegexValidator(
                r'^(\+\d\d?)?\(\d{3}\)(\d-?){7}$',
                message="Phone number should be in format +1(111)222-33-44"
            )
        ]
    )
    enroll_date = models.DateField(default=datetime.datetime.today())
    graduate_date = models.DateField(default=datetime.datetime.today)
    inn = models.PositiveIntegerField(unique=True, null=True)

    @classmethod
    def generate_students(cls, count):
        faker = Faker()

        for _ in range(count):
            s = Student()
            s.first_name = faker.first_name()
            s.last_name = faker.last_name()
            s.age = random.randint(18, 80)

            s.save()

    def __str__(self):
        return f"Student({self.id}) {self.first_name} {self.last_name} " \
               f"{self.age} {self.phone_number} " \
               f"{self.enroll_date} {self.graduate_date}"

    @property
    def name(self):
        return f'{self.first_name} {self.last_name}'

    def get_update_link(self):
        return reverse('students:update_students',kwargs={'id':self.id})

students/forms.py
import django_filters
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from students.models import Student


class StudentFilter(django_filters.FilterSet):
    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'age']


class StudentBaseForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

    def clean(self):
        result = super().clean()

        enroll_date = self.cleaned_data['enroll_date']
        graduate_date = self.cleaned_data['graduate_date']

        if enroll_date > graduate_date:
            raise ValidationError("Enroll date cannot be less "
                                  "than gradate date")

        return result

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']

        has_phone_number_qs = Student.objects.filter(
            phone_number=phone_number
        )

        if self.instance:
            has_phone_number_qs = has_phone_number_qs.exclude(
                id=self.instance.id
            )

        if has_phone_number_qs.exists():
            raise ValidationError("Phone number is not unique")

        return phone_number


class StudentCreateForm(StudentBaseForm):
    pass


class StudentUpdateForm(StudentBaseForm):
    class Meta:
        model = Student
        exclude = ['age']

core_lms/views.py
from django.shortcuts import render


# Create your views here.

def index(request):
    return render(request, 'index.html')

students/views.py
# Create your views here.
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from students.forms import StudentCreateForm, StudentUpdateForm, StudentFilter
from students.models import Student


def get_students(request):
    qs = Student.objects.all()
    # params = [
    #     'first_name',
    #     'first_name__startswith',
    #     'first_name__endswith',
    #     'first_name__contains',
    #     'last_name',
    #     'age',
    #     'age__gt',
    #     'age__lt',
    # ]
    #
    # query = {}
    #
    # for param_name in params:
    #     param_value = request.GET.get(param_name)
    #     if param_value:
    #         if ',' in param_value and '__' not in param_name:
    #             param_values = param_value.split(',')
    #             query[param_name + '__in'] = param_values
    #         else:
    #             query[param_name] = param_value
    #
    # try:
    #     qs = qs.filter(**query)
    # except ValueError as e:
    #     return HttpResponse(f"Error wrong input data. {str(e)}", status=400)

    qs = qs.order_by('-id')

    students_filter = StudentFilter(data=request.GET, queryset=qs)

    return render(request, 'list_students.html', {
        'args': request.GET,
        'filter': students_filter
    })


@csrf_exempt
def create_student(request):
    if request.method == 'POST':
        form = StudentCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('students:list_students'))
    else:
        form = StudentCreateForm()

    return render(request, 'create_student.html', {
        'form': form
    })


@csrf_exempt
def update_student(request, id):
    student = get_object_or_404(Student, id=id)

    if request.method == 'POST':
        form = StudentUpdateForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('students:list_students'))
    else:
        form = StudentUpdateForm(instance=student)

    return render(request, 'edit_student.html', {
        'form': form
    })


@csrf_exempt
def delete_student(request, id):
    student = get_object_or_404(Student, id=id)

    if request.method == 'POST':
        student.delete()
        return HttpResponseRedirect(reverse('students:list_students'))

    return render(
        request,
        'delete_student.html',
        {
            'student': student
        }
    )


# Not used
def delete_student_no_confirmation(request, id):
    try:
        student = Student.objects.get(id=id)
        student.delete()
    except Student.DoesNotExist:
        pass
    return HttpResponseRedirect(reverse('students:list_students'))

students/templates/_header_menu.html
{#<a href="/">LMS</a> | <a href="{% url 'students:list_students' %}">Students</a>#}


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">LMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'students:list_students' %}">Students</a>
        </li>
{#        <li class="nav-item">#}
{#          <a class="nav-link" href="#">Link</a>#}
{#        </li>#}
{#        <li class="nav-item dropdown">#}
{#          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">#}
{#            Dropdown#}
{#          </a>#}
{#          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#            <li><a class="dropdown-item" href="#">Action</a></li>#}
{#            <li><a class="dropdown-item" href="#">Another action</a></li>#}
{#            <li><hr class="dropdown-divider"></li>#}
{#            <li><a class="dropdown-item" href="#">Something else here</a></li>#}
{#          </ul>#}
{#        </li>#}
{#        <li class="nav-item">#}
{#          <a class="nav-link disabled">Disabled</a>#}
{#        </li>#}
      </ul>
{#      <form class="d-flex">#}
{#        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">#}
{#        <button class="btn btn-outline-success" type="submit">Search</button>#}
{#      </form>#}
    </div>
  </div>
</nav>

students/templates/create_student.html
{% extends '_base.html' %}

{% block main %}
    <form method="post">
        {{ form.as_p }}
        <p>
            <button type="submit">Create Student</button>
        </p>
    </form>
{% endblock %}

students/templates/delete_student.html
{% extends '_base.html' %}

{% block main %}
    <form method="post">
        <p>Do you want to delete student {{ student.name }}?</p>
        <p>
            <button class="btn btn-danger" type="submit">Delete</button>
            <a class="btn btn-info" href="{% url 'students:list_students' %}">Cancel</a>
        </p>
    </form>
{% endblock %}

students/templates/edit_student.html
{% extends '_base.html' %}

{% block main %}
    <form method="post">
        {{ form.as_p }}
        <p>
            <button type="submit">Update Student</button>
        </p>
    </form>
{% endblock %}

students/templates/list_students.html
{% extends '_base.html' %}

{% block main %}
    <form>
        <p>Search students</p>
        {{ filter.form.as_p }}
        <p>
            <button type="submit">Search</button>
        </p>
    </form>
    <br>
    <a href="{% url 'students:create_students' %}">Add new student</a><br>

    <p id="main-paragraph">Text 1</p>
    <p> <strong class="text-red">Text 2</strong></p>
    <table class="table table-striped">
        <tr>
            <th><strong>First Name</strong></th>
            <th class="text-red border-blue">Last Name</th>
            <th>INN</th>
            <th></th>
        </tr>

        {% for student in filter.qs|slice:":20" %}
            <tr>
                <td>{{ student.first_name|capfirst }}</td>
                <td>{{ student.last_name|title }}</td>
                <td>{{ student.inn }}</td>
                <td>
                    <a href="{% url 'students:update_students' id=student.id %}">✎</a>
                    <a href="{% url 'students:delete_students' id=student.id %}">🗑</a>
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>STUDENTS</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">

    <style type="text/css">


    </style>
</head>
<body>
    {% include '_header_menu.html' %}

    <div class="container">
        {% block main %}
        {% endblock %}
    </div>
</body>
</html>

templates/index.html
{% extends '_base.html' %}
{% block main %}
    <h1>Welcome to LMS!</h1>
{% endblock %}